LOCATIONS = {
    "delhi": {
        "name": "Delhi",
        "state": "Delhi",
        "lat": 28.6139,
        "lon": 77.2090,
        "x": "46%",
        "y": "24%",
        "tagline": "Capital city with monuments, markets, and a fast-moving urban rhythm.",
        "best_time": "October to March",
        "places": ["India Gate", "Red Fort", "Qutub Minar", "Lotus Temple"],
    },
    "mumbai": {
        "name": "Mumbai",
        "state": "Maharashtra",
        "lat": 19.0760,
        "lon": 72.8777,
        "x": "30%",
        "y": "51%",
        "tagline": "Seafront energy, cinema culture, and iconic colonial-era architecture.",
        "best_time": "November to February",
        "places": ["Gateway of India", "Marine Drive", "Juhu Beach", "Elephanta Caves"],
    },
    "jaipur": {
        "name": "Jaipur",
        "state": "Rajasthan",
        "lat": 26.9124,
        "lon": 75.7873,
        "x": "38%",
        "y": "31%",
        "tagline": "Pink City grandeur with forts, palaces, and colorful bazaars.",
        "best_time": "October to March",
        "places": ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"],
    },
    "varanasi": {
        "name": "Varanasi",
        "state": "Uttar Pradesh",
        "lat": 25.3176,
        "lon": 82.9739,
        "x": "56%",
        "y": "33%",
        "tagline": "Ancient ghats, spiritual traditions, and timeless riverside scenes.",
        "best_time": "October to February",
        "places": ["Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sarnath", "Assi Ghat"],
    },
    "kolkata": {
        "name": "Kolkata",
        "state": "West Bengal",
        "lat": 22.5726,
        "lon": 88.3639,
        "x": "68%",
        "y": "42%",
        "tagline": "Literary spirit, colonial heritage, and rich Bengali food culture.",
        "best_time": "October to February",
        "places": ["Victoria Memorial", "Howrah Bridge", "Dakshineswar Temple", "Park Street"],
    },
    "goa": {
        "name": "Panaji",
        "state": "Goa",
        "lat": 15.4909,
        "lon": 73.8278,
        "x": "29%",
        "y": "64%",
        "tagline": "Beach escapes, laid-back streets, and Portuguese-era charm.",
        "best_time": "November to February",
        "places": ["Miramar Beach", "Fontainhas", "Basilica of Bom Jesus", "Dona Paula"],
    },
    "hyderabad": {
        "name": "Hyderabad",
        "state": "Telangana",
        "lat": 17.3850,
        "lon": 78.4867,
        "x": "45%",
        "y": "59%",
        "tagline": "Historic minarets, biryani trails, and growing tech corridors.",
        "best_time": "October to February",
        "places": ["Charminar", "Golconda Fort", "Hussain Sagar", "Salar Jung Museum"],
    },
    "bengaluru": {
        "name": "Bengaluru",
        "state": "Karnataka",
        "lat": 12.9716,
        "lon": 77.5946,
        "x": "39%",
        "y": "71%",
        "tagline": "Garden city weather, startup culture, and green urban spaces.",
        "best_time": "October to February",
        "places": ["Lalbagh", "Cubbon Park", "Bangalore Palace", "ISKCON Temple"],
    },
    "chennai": {
        "name": "Chennai",
        "state": "Tamil Nadu",
        "lat": 13.0827,
        "lon": 80.2707,
        "x": "52%",
        "y": "78%",
        "tagline": "Temple heritage, coastal drives, and classical South Indian culture.",
        "best_time": "November to February",
        "places": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "San Thome Basilica"],
    },
    "kochi": {
        "name": "Kochi",
        "state": "Kerala",
        "lat": 9.9312,
        "lon": 76.2673,
        "x": "38%",
        "y": "85%",
        "tagline": "Backwaters gateway with spice history and waterfront art districts.",
        "best_time": "September to March",
        "places": ["Fort Kochi", "Chinese Fishing Nets", "Mattancherry Palace", "Marine Drive"],
    },
}
