LOCATIONS = {
    "delhi": {
        "name": "Delhi",
        "state": "Delhi",
        "lat": 28.6139,
        "lon": 77.2090,
        "x": "46%",
        "y": "24%",
        "tagline": "Capital city with monuments, markets, and a fast-moving urban rhythm.",
        "best_time": "October to March",
        "places": ["India Gate", "Red Fort", "Qutub Minar", "Lotus Temple"],
    },
    "mumbai": {
        "name": "Mumbai",
        "state": "Maharashtra",
        "lat": 19.0760,
        "lon": 72.8777,
        "x": "30%",
        "y": "51%",
        "tagline": "Seafront energy, cinema culture, and iconic colonial-era architecture.",
        "best_time": "November to February",
        "places": ["Gateway of India", "Marine Drive", "Juhu Beach", "Elephanta Caves"],
    },
    "jaipur": {
        "name": "Jaipur",
        "state": "Rajasthan",
        "lat": 26.9124,
        "lon": 75.7873,
        "x": "38%",
        "y": "31%",
        "tagline": "Pink City grandeur with forts, palaces, and colorful bazaars.",
        "best_time": "October to March",
        "places": ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"],
    },
    "varanasi": {
        "name": "Varanasi",
        "state": "Uttar Pradesh",
        "lat": 25.3176,
        "lon": 82.9739,
        "x": "56%",
        "y": "33%",
        "tagline": "Ancient ghats, spiritual traditions, and timeless riverside scenes.",
        "best_time": "October to February",
        "places": ["Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sarnath", "Assi Ghat"],
    },
    "kolkata": {
        "name": "Kolkata",
        "state": "West Bengal",
        "lat": 22.5726,
        "lon": 88.3639,
        "x": "68%",
        "y": "42%",
        "tagline": "Literary spirit, colonial heritage, and rich Bengali food culture.",
        "best_time": "October to February",
        "places": ["Victoria Memorial", "Howrah Bridge", "Dakshineswar Temple", "Park Street"],
    },
    "goa": {
        "name": "Panaji",
        "state": "Goa",
        "lat": 15.4909,
        "lon": 73.8278,
        "x": "29%",
        "y": "64%",
        "tagline": "Beach escapes, laid-back streets, and Portuguese-era charm.",
        "best_time": "November to February",
        "places": ["Miramar Beach", "Fontainhas", "Basilica of Bom Jesus", "Dona Paula"],
    },
    "hyderabad": {
        "name": "Hyderabad",
        "state": "Telangana",
        "lat": 17.3850,
        "lon": 78.4867,
        "x": "45%",
        "y": "59%",
        "tagline": "Historic minarets, biryani trails, and growing tech corridors.",
        "best_time": "October to February",
        "places": ["Charminar", "Golconda Fort", "Hussain Sagar", "Salar Jung Museum"],
    },
    "bengaluru": {
        "name": "Bengaluru",
        "state": "Karnataka",
        "lat": 12.9716,
        "lon": 77.5946,
        "x": "39%",
        "y": "71%",
        "tagline": "Garden city weather, startup culture, and green urban spaces.",
        "best_time": "October to February",
        "places": ["Lalbagh", "Cubbon Park", "Bangalore Palace", "ISKCON Temple"],
    },
    "chennai": {
        "name": "Chennai",
        "state": "Tamil Nadu",
        "lat": 13.0827,
        "lon": 80.2707,
        "x": "52%",
        "y": "78%",
        "tagline": "Temple heritage, coastal drives, and classical South Indian culture.",
        "best_time": "November to February",
        "places": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "San Thome Basilica"],
    },
    "kochi": {
        "name": "Kochi",
        "state": "Kerala",
        "lat": 9.9312,
        "lon": 76.2673,
        "x": "38%",
        "y": "85%",
        "tagline": "Backwaters gateway with spice history and waterfront art districts.",
        "best_time": "September to March",
        "places": ["Fort Kochi", "Chinese Fishing Nets", "Mattancherry Palace", "Marine Drive"],
    },
    "amritsar": {
        "name": "Amritsar",
        "state": "Punjab",
        "lat": 31.6340,
        "lon": 74.8723,
        "x": "32%",
        "y": "18%",
        "tagline": "Sacred landmarks, Punjabi hospitality, and unforgettable food streets.",
        "best_time": "October to March",
        "places": ["Golden Temple", "Jallianwala Bagh", "Wagah Border", "Partition Museum"],
    },
    "shimla": {
        "name": "Shimla",
        "state": "Himachal Pradesh",
        "lat": 31.1048,
        "lon": 77.1734,
        "x": "43%",
        "y": "17%",
        "tagline": "Cool mountain air, colonial promenades, and Himalayan viewpoints.",
        "best_time": "March to June",
        "places": ["Mall Road", "Jakhoo Temple", "Kufri", "The Ridge"],
    },
    "ahmedabad": {
        "name": "Ahmedabad",
        "state": "Gujarat",
        "lat": 23.0225,
        "lon": 72.5714,
        "x": "24%",
        "y": "39%",
        "tagline": "Heritage pols, riverfront evenings, and a strong design culture.",
        "best_time": "November to February",
        "places": ["Sabarmati Ashram", "Kankaria Lake", "Adalaj Stepwell", "Riverfront"],
    },
    "bhopal": {
        "name": "Bhopal",
        "state": "Madhya Pradesh",
        "lat": 23.2599,
        "lon": 77.4126,
        "x": "43%",
        "y": "43%",
        "tagline": "Lake city calm with historic mosques and nearby heritage sites.",
        "best_time": "October to March",
        "places": ["Upper Lake", "Van Vihar", "Taj-ul-Masajid", "Sanchi Stupa"],
    },
    "lucknow": {
        "name": "Lucknow",
        "state": "Uttar Pradesh",
        "lat": 26.8467,
        "lon": 80.9462,
        "x": "52%",
        "y": "28%",
        "tagline": "Nawabi elegance, kebab trails, and grand Indo-Islamic architecture.",
        "best_time": "October to March",
        "places": ["Bara Imambara", "Rumi Darwaza", "Hazratganj", "Ambedkar Park"],
    },
    "patna": {
        "name": "Patna",
        "state": "Bihar",
        "lat": 25.5941,
        "lon": 85.1376,
        "x": "61%",
        "y": "34%",
        "tagline": "Historic river city with deep roots in ancient Indian history.",
        "best_time": "October to March",
        "places": ["Golghar", "Bihar Museum", "Takht Sri Patna Sahib", "Eco Park"],
    },
    "guwahati": {
        "name": "Guwahati",
        "state": "Assam",
        "lat": 26.1445,
        "lon": 91.7362,
        "x": "80%",
        "y": "30%",
        "tagline": "Gateway to the Northeast with hills, riverfront views, and temples.",
        "best_time": "October to April",
        "places": ["Kamakhya Temple", "Umananda Temple", "Brahmaputra Cruise", "Pobitora"],
    },
    "srinagar": {
        "name": "Srinagar",
        "state": "Jammu and Kashmir",
        "lat": 34.0837,
        "lon": 74.7973,
        "x": "35%",
        "y": "8%",
        "tagline": "Lakeside houseboats, gardens, and snow-framed valley scenery.",
        "best_time": "April to October",
        "places": ["Dal Lake", "Mughal Gardens", "Shankaracharya Temple", "Nishat Bagh"],
    },
    "rishikesh": {
        "name": "Rishikesh",
        "state": "Uttarakhand",
        "lat": 30.0869,
        "lon": 78.2676,
        "x": "48%",
        "y": "20%",
        "tagline": "River adventures, yoga retreats, and Himalayan foothill calm.",
        "best_time": "September to April",
        "places": ["Lakshman Jhula", "Triveni Ghat", "Neer Garh Waterfall", "Ram Jhula"],
    },
    "puri": {
        "name": "Puri",
        "state": "Odisha",
        "lat": 19.8135,
        "lon": 85.8312,
        "x": "62%",
        "y": "56%",
        "tagline": "Temple town devotion paired with broad beaches and sea breezes.",
        "best_time": "October to February",
        "places": ["Jagannath Temple", "Puri Beach", "Konark Sun Temple", "Chilika Lake"],
    },
    "madurai": {
        "name": "Madurai",
        "state": "Tamil Nadu",
        "lat": 9.9252,
        "lon": 78.1198,
        "x": "46%",
        "y": "88%",
        "tagline": "Temple city drama, night markets, and ancient Tamil heritage.",
        "best_time": "October to March",
        "places": ["Meenakshi Temple", "Thirumalai Nayakkar Mahal", "Gandhi Museum", "Azhagar Kovil"],
    },
}
